name       : perl-parse-yapp
version    : '1.21'
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/W/WB/WBRASWELL/Parse-Yapp-1.21.tar.gz : 3810e998308fba2e0f4f26043035032b027ce51ce5c8a52a8b8e340ca65f13e5
homepage   : https://metacpan.org/pod/Parse::Yapp
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl extension for generating and using LALR parsers.
description: |
    Parse::Yapp (Yet Another Perl Parser compiler) is a collection of modules that let you generate and use yacc like thread safe (reentrant) parsers with perl object oriented interface.
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |-
    %perl_build test
